name: Deploy MkDocs Site

on:
  push:
    branches:
      - master  # Change this if using a different branch
  workflow_dispatch:  # Allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Or read, or both
      pull-requests: write # If you need to interact with pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version-file: .python-version

      - name: Install dependencies
        run: |          
          sudo apt update
          sudo apt install -y rustc pngquant libjpeg-turbo-progs nodejs
          cargo install oxipng
          npm install --no-fund -f svgo html-minifier-terser postcss cssnano postcss-svgo postcss-cli uglify-js

      - name: Build site
        run: |
          uv sync
          uv run mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
